name: popster-dev
channels:
- anjos
- https://www.idiap.ch/software/bob/conda/label/beta
- https://www.idiap.ch/software/bob/conda
- defaults
dependencies:
- python=3.6
- six
- ncurses
- docopt
- exifread
- pillow
- pymediainfo
- watchdog
- bob.buildout
- ipdb
