{% set name = "zc.buildout" %}
{% set version = "2.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/z/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: b833d0a9d69835b883fda5553c66e9ce

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

  entry_points:
    - buildout=zc.buildout.buildout:main

requirements:
  build:
    - python
    - setuptools >=36.4

  run:
    - python
    - setuptools >=36.4

test:
  imports:
    - zc
    - zc.buildout

  commands:
    - buildout --help

about:
  home: http://buildout.org
  license: Zope Public License
  summary: 'System for managing development buildouts'
