{% set version = "2.9.2" %}

package:
  name: zc.buildout
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/buildout/buildout.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

  entry_points:
    - buildout=zc.buildout.buildout:main

requirements:
  build:
    - python
    - setuptools >=8.0

  run:
    - python
    - setuptools >=8.0

test:
  imports:
    - zc
    - zc.buildout

  commands:
    - buildout --help

about:
  home: http://buildout.org
  license: Zope Public License
  summary: 'System for managing development buildouts'
