{% set name="pymediainfo" %}
{% set version="4.1" %}
{% set sha256="ed6a8f3dcd255895021d40d1299be333a1bead3dbe8df4cbe1a863ba8fee1756" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - mediainfo

test:
  imports:
    - {{ name }}

  requires:
    - pytest

  source_files:
    - tests/*

  commands:
    - pytest

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT License
  summary: A Python wrapper for the mediainfo library
  license_family: MIT
