{% set name="pymediainfo" %}
{% set version="4.2.1" %}
{% set sha256="392d99d6bf74046ebaa2f7036d92d5327611d27532a384540e9310a62b8be26d" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - mediainfo

test:
  imports:
    - {{ name }}

  requires:
    - pytest

  source_files:
    - tests/*

  commands:
    - pytest

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT License
  summary: A Python wrapper for the mediainfo library
  license_family: MIT
