{% set name="pymediainfo" %}
{% set version="3.0" %}
{% set sha256="e76cc5525c3fc5cba61073e12365dc06f303b261d8f923aaa6eac09bf8fab245" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - mediainfo

test:
  imports:
    - {{ name }}

  requires:
    - pytest

  source_files:
    - tests/*

  commands:
    - pytest

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT License
  summary: A Python wrapper for the mediainfo library
  license_family: MIT
