{% set name="pymediainfo" %}
{% set version="2.1.9" %}
{% set md5="993428f64822c9826ccec0108d6edc0c" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - mediainfo

test:
  imports:
    - {{ name }}

  requires:
    - nose

  source_files:
    - tests/*

  commands:
    - nosetests -sv tests

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT License
  summary: A Python wrapper for the mediainfo library
  license_family: MIT
