{% set name = "watchdog" %}
{% set version = "0.9.0" %}
{% set hash_type = "sha256" %}
{% set hash = "965f658d0732de3188211932aeb0bb457587f04f63ab4c1e33eab878e9de961d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argh >=0.24.1
    - pathtools >=0.1.1
    - pyyaml >=3.10

test:
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.tricks
    - watchdog.utils
  commands:
    - watchmedo --help

about:
  home: http://github.com/gorakhargosh/watchdog
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Filesystem events monitoring'
  doc_url: http://pythonhosted.org/watchdog

extra:
  recipe-maintainers:
    - goanpeca
