{% set name="MediaInfo" %}
{% set version="20.09" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}_CLI_{{ version }}_GNU_FromSource.tar.bz2
  url: https://mediaarea.net/download/binary/{{ name | lower }}/{{ version }}/{{ name }}_CLI_{{ version }}_GNU_FromSource.tar.bz2
  sha256: a252aa61dc1f4caeb9dc76d82292cadc993fb112a402dffd9e442e7fdf76e88e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config # [unix]
  host:
    - zlib 1.2.*
    - curl
  run:
    - zlib
    - curl

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name | lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name | lower }}  # [osx]

about:
  license: BSD
  home: https://mediaarea.net/
  summary: {{ name }} is a convenient unified display of the most relevant technical and tag data for video and audio files.

extra:
  recipe-maintainers:
    - anjos
