{% set name="MediaInfo" %}
{% set version="0.7.95" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}_CLI_{{ version }}_GNU_FromSource.tar.bz2
  url: https://mediaarea.net/download/binary/{{ name | lower }}/{{ version }}/{{ name }}_CLI_{{ version }}_GNU_FromSource.tar.bz2
  md5: 5452a560fb22c2e56d3e33cd1006f0e9

build:
  number: 0

requirements:
  build:
    - pkg-config [unix]
    - zlib 1.2.*
    - curl
    - gcc 4.8.5
    - libgcc 4.8.5

  run:
    - zlib 1.2.*
    - curl 7.52.*
    - libgcc 4.8.5

about:
  license: BSD
  home: https://mediaarea.net/
  summary: {{ name }} is a convenient unified display of the most relevant technical and tag data for video and audio files.

extra:
  recipe-maintainers:
    - anjos
