{% set name = "ExifRead" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ianare/exif-py.git
  git_rev: {{ version }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - exifread

about:
  home: https://github.com/ianare/exif-py
  license: BSD
  summary: Easy to use Python module to extract Exif metadata from tiff and jpeg files

extra:
  recipe-maintainers:
    - anjos
