{% set name = 'popster' %}
{% set version = load_setup_py_data()['version'] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - watch = popster.watch:main
    - check_date = popster.check_date:main
    - heic_to_jpeg = popster.heic_to_jpeg:main
    - deduplicate = popster.deduplicate:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - docopt
    - watchdog
    - exifread
    - pymediainfo
    - pillow
    - tqdm
    - requests

test:
  imports:
    - {{ name }}

  requires:
    - nose
    - coverage

  commands:
    - watch --help
    - check_date --help
    - heic_to_jpeg --help
    - deduplicate --help
    - nosetests -sv --with-coverage --cover-package={{ name }} {{ name }}

about:
  home: https://github.com/anjos/popster
  license: GPLv3
  summary: A pythonic photo importer for my QNAP NAS
  license_family: GPL
