{% set data = load_setup_py_data() %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ../

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - watch = popster.watch:main
    - check_date = popster.check_date:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - docopt
    - watchdog
    - exifread
    - pymediainfo
    - pillow

test:
  imports:
    - {{ data['name'] }}

  requires:
    - nose
    - coverage

  commands:
    - watch --help
    - check_date --help
    - nosetests -sv --with-coverage --cover-package={{ data['name'] }} {{ data['name'] }}

about:
  home: https://github.com/anjos/popster
  license: GPLv3
  summary: A pythonic photo importer for my QNAP NAS
  license_family: GPL
